name: base
channels:
  - defaults
  - pytorch
dependencies:
  - conda
  - python=3.9
  - numba
  - pytorch:pytorch==1.11.0
  - pip
  - ipykernel
  - pytorch:cudatoolkit=11.3
  - numpy=1.21
  - pytorch:torchvision==0.12.0
  - pytorch:torchaudio==0.11.0
prefix: /opt/conda

# conda env update -f environment.yml --prune
